---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv-data
  labels:
    type: local
    storage: "minecraft-data"
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/minecraft-server/1.16/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc-data
spec:
  storageClassName: manual
  selector:
    matchLabels:
      storage: "minecraft-data"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
