---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr-deployment
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: ghcr.io/linuxserver/radarr
        ports:
        - containerPort: 7878
        env:
        - name: PUID
          value: '1002'
        - name: PGID
          value: '1001'
        - name: TZ
          value: Europe/Paris
        volumeMounts:
        - name: data
          mountPath: /complete
        - name: downloads
          mountPath: /downloads
        - name: config
          mountPath: /config
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-data
      - name: downloads
        persistentVolumeClaim:
          claimName: pvc-downloads
      - name: config
        persistentVolumeClaim:
          claimName: radarr-pvc-config
      - name: localtime
        persistentVolumeClaim:
          claimName: pvc-localtime