---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv-config
  labels:
    type: local
    storage: "sonarr-config"
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/plex/storage/homemedia/config/sonarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pvc-config
spec:
  storageClassName: manual
  selector:
    matchLabels:
      storage: "sonarr-config"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi