---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv-config
  labels:
    type: local
    storage: "plex-config"
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/plex/storage/homemedia/config/plex/db"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv-transcode
  labels:
    type: local
    storage: "transcode"
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/plex/storage/homemedia/config/plex/transcode"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-config
spec:
  storageClassName: manual
  selector:
    matchLabels:
      storage: "plex-config"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-transcode
spec:
  storageClassName: manual
  selector:
    matchLabels:
      storage: "transcode"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
