---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge-deployment
  labels:
    app: deluge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
      - name: deluge
        image: ghcr.io/linuxserver/deluge
        ports:
        - containerPort: 8112
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: Europe/Paris
        volumeMounts:
        - name: downloads
          mountPath: /downloads
        - name: config
          mountPath: /config
      volumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: pvc-downloads
      - name: config
        persistentVolumeClaim:
          claimName: deluge-pvc-config