---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-pv-config
  labels:
    type: local
    storage: deluge-config
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/plex/storage/homemedia/config/deluge"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-pvc-config
spec:
  storageClassName: manual
  selector:
    matchLabels:
      storage: "deluge-config"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
