---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
  labels:
    type: local
    storage: data
spec:
  storageClassName: manual
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sda1/complete"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
spec:
  storageClassName: manual
  selector:
    matchLabels:
      storage: "data"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Gi