---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-localtime
  labels:
    type: local
    storage: "localtime"
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/etc/localtime"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-localtime
spec:
  storageClassName: manual
  selector:
    matchLabels:
      storage: "localtime"
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi