---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-pv-config
  labels:
    type: local
    storage: "jackett-config"
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/plex/storage/homemedia/config/jackett"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-pvc-config
spec:
  storageClassName: manual
  selector:
    matchLabels:
      storage: "jackett-config"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi