---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-downloads
  labels:
    type: local
    storage: downloads
spec:
  storageClassName: manual
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sda1/downloads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-downloads
spec:
  storageClassName: manual
  selector:
    matchLabels:
      storage: "downloads"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv
    server: 192.168.0.39
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi