---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: overseerr-pv-config
  labels:
    type: local
    storage: config
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/plex/storage/homemedia/config/overseerr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-pvc-config
spec:
  storageClassName: manual
  selector:
    matchLabels:
      storage: "config"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi