---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-pv-config
  labels:
    type: local
    storage: radarr-config
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/plex/storage/homemedia/config/radarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc-config
spec:
  storageClassName: manual
  selector:
    matchLabels:
      storage: "radarr-config"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi